### ISSUE TITLE
p7zip is installed, but seven_zip_ruby still try to compile and failed

### ISSUE THREAD

**Issue by phuongnd08** [masamitsu-murase/seven_zip_ruby#11]
I'm already installed `p7zip` on my CentOS server. Then I tried to install seven_zip_ruby:

```
Building native extensions.  This could take a while...
/usr/local/rbenv/versions/2.1.1/bin/ruby extconf.rb
checking for ruby/thread.h... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/local/rbenv/versions/2.1.1/bin/ruby
extconf.rb:156:in `main': C++11 is not supported by the compiler. (RuntimeError)
    from extconf.rb:179:in `<main>'
ERROR:  Error installing seven_zip_ruby:
    ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
extconf failed, exit code 1
```

Is it possible to tell seven_zip_ruby to use the existing p7zip instead of trying to compile?

**Comment by luaxlou** [comment]
@phuongnd08 you could see this article: [http://hiltmon.com/blog/2015/08/09/c-plus-plus-11-on-centos-6-dot-6/](http://hiltmon.com/blog/2015/08/09/c-plus-plus-11-on-centos-6-dot-6/),i'd just resolve it.
