### ISSUE TITLE
Support Ruby 2.4

### ISSUE THREAD

**Issue by orgads** [masamitsu-murase/seven_zip_ruby#27]
Hi,

Ruby 2.4 is currently unsupported for this gem. Can you please add support for it?

Building native extensions doesn't help. require still fails:
```
irb(main):001:0> require 'seven_zip_ruby'
RuntimeError: Failed to initialize SevenZipRuby
        from D:/Ruby/lib/ruby/gems/2.4.0/gems/seven_zip_ruby-1.2.5/lib/seven_zip_ruby.rb:19:in `<top (required)>'
        from D:/Ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from D:/Ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from D:/Ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from (irb):1
        from D:/Ruby/bin/irb.cmd:19:in `<main>'
```

**Comment by masamitsu-murase** [comment]
1.3.0 supports Ruby 2.4 and later versions.
Thanks.
